### ISSUE TITLE
View window is tiny or doesn't show

### ISSUE THREAD

**Issue by pna837** [pna837/ADP#5]
![screen shot 2013-11-08 at 10 14 03 pm](https://f.cloud.github.com/assets/4483892/1505811/15c43c74-48ed-11e3-8fe0-63329f02ac8c.png)
![screen shot 2013-11-08 at 10 12 40 pm](https://f.cloud.github.com/assets/4483892/1505812/15c6cd22-48ed-11e3-8d53-2142aef01581.png)

View window is small for Safari. Doesn't seem to display for me within Chrome, but area appears small also.

**Comment by pna837** [comment]
Similar problem w/ Firefox. It doesn't show the document at all.
![screen shot 2013-11-08 at 10 18 45 pm](https://f.cloud.github.com/assets/4483892/1505817/bdc59a6c-48ed-11e3-97d9-c0cf8da2b96a.png)

**Comment by ayafor** [comment]
Feature will be removed (wasn't working properly in all browsers!).
